kind: ConfigMap
apiVersion: v1
metadata:
  name: mq-no-security
  namespace: mq
data:
  config.mqsc: |-
    DEFINE QLOCAL('TO.KAFKA') REPLACE

    DEFINE CHANNEL(KAFKASVRCONN) CHLTYPE(SVRCONN)

    ALTER QMGR CHLAUTH (DISABLED)

    REFRESH SECURITY TYPE(CONNAUTH)
