apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq-no-security
  namespace: mq
spec:
  license:
    accept: true
    license: L-RJON-BUVMQX
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    metrics:
      enabled: true
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: '1'
        memory: 1Gi
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    name: QM1
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: IfNotPresent
    debug: false
    mqsc:
      - configMap:
          items:
            - config.mqsc
          name: mq-no-security
    logFormat: Basic
    availability:
      type: SingleInstance
    storage:
      persistedData:
        enabled: false
      queueManager:
        type: ephemeral
      recoveryLogs:
        enabled: false
  securityContext:
    initVolumeAsRoot: false
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
          resources: {}
  terminationGracePeriodSeconds: 30
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ''
  version: 9.2.0.4-r1-eus
  web:
    enabled: true