apiVersion: eventstreams.ibm.com/v1beta1
kind: EventStreams
metadata:
  name: dev-poc
  namespace: eventstreams
spec:
  security:
    internalTls: NONE
  license:
    accept: true
    use: CloudPakForIntegrationNonProduction
  strimziOverrides:
    kafka:
      config:
        inter.broker.protocol.version: '2.6'
        interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
        log.message.format.version: '2.6'
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      listeners:
        plain: {}
      metrics: {}
      replicas: 1
      storage:
        type: ephemeral
    zookeeper:
      metrics: {}
      replicas: 1
      storage:
        type: ephemeral
  adminUI: {}
  restProducer: {}
  apicurioRegistry: {}
  adminApi: {}
  collector: {}
  version: 10.2.1-eus